config/routes.rb
Rails.application.routes.draw do
  resources :students do
    collection { post :import } 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  def self.search(support)
    if support.present?
      where(["support LIKE ?", support])
    else
      all
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Student.create! row.to_hash
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.search(params[:support]).order(:grade, :name)
    @supports = Student.uniq.pluck(:support)
    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Student.import(params[:file])
    redirect_to root_url, notice: "Students imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:st_id, :name, :gender, :program, :support, :school, :dob, :doj)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def grade(int)
    case int
    when -2
      return "Nursery"
    when -1
      return "LKG"
    when 0
      return "UKG"
    when 1
      return "I"
    when 2
      return "II"
    when 3
      return "III"
    when 4
      return "IV"
    when 5
      return "V"
    when 6
      return "VI"
    when 7
      return "VII"
    when 8
      return "VIII"
    when 9
      return "IX"
    when 10
      return "X"
    when 11
      return "XI"
    when 12
      return "XII"
    when 13
      return "College"
    when 14
      return "N/A"
    else
      return "N/A"
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sunshine Society
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    =# stylesheet_link_tag 'blueprint/print', :media => 'print'
    = javascript_include_tag 'application'
  %body
    .container-fluid
      = yield

app/views/students/_form.html.haml
= simple_form_for @student, html: { class: 'form-horizontal' } do |f|
  - if @student.errors.any?
    #errors
      %p
        = @student.errors.count
        Prevented this recipe from Saving
      %ul
        - @student.erors.full_messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :st_id, label: "Sudent ID", input_html: {class: 'form-control'}
    = f.input :name, input_html: {class: 'form-control'}
    = f.input :gender, input_html: {class: 'form-control'}
    = f.input :program, input_html: {class: 'form-control'}
    = f.input :support, input_html: {class: 'form-control'}
    = f.input :school, input_html: {class: 'form-control'}
    = f.input :grade, input_html: {class: 'form-control'}
    = f.input :dob, label: "Date Of Birth", input_html: {class: 'form-control'}
    = f.input :doj, label: "Date Of Joining", input_html: {class: 'form-control'}
  = f.button :submit, class: "btn btn-primary"

app/views/students/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1 Edit Student Details
    .col-md-6
      = render 'form', student: @student
      = link_to 'Show', @student
      |
      = link_to 'Back', students_path
    %br
    %br

app/views/students/index.html.haml
%p#notice= notice
%h1#print1
  %input{:name => "header", :type => "text"}/

#print2
  %br
  = form_tag students_path, :method => :get, :class => 'form-search' do
    .input
      = select_tag(:support, options_for_select(@supports), :prompt => "Select Program", :include_blank => true, input_html: {class: 'form-control'})
      - @var = :support
      = submit_tag "Search"
%br
#print3
  #grpChkBox
    %p
      %input{:name => "id", :type => "checkbox"}/
      ID
    %p
      %input{:name => "name", :type => "checkbox"}/
      Name
    %p
      %input{:name => "gender", :type => "checkbox"}/
      Gender
    %p
      %input{:name => "program", :type => "checkbox"}/
      Program
    %p
      %input{:name => "support", :type => "checkbox"}/
      Support
    %p
      %input{:name => "school", :type => "checkbox"}/
      School
    %p
      %input{:name => "class", :type => "checkbox"}/
      Class
    %p
      %input{:name => "dob", :type => "checkbox"}/
      DoB
    %p
      %input{:name => "doj", :type => "checkbox"}/
      DoJ
    %p
      %input{:name => "attendance", :type => "checkbox"}/
      Attendance
%br
%table.table.table-striped.table-bordered#someTable
  %thead
    %tr
      %th.sno SNo.
      %th.id ID
      %th.name Name
      %th.gender Gender
      %th.program Program
      %th.support Support
      %th.school School
      %th.class Class
      %th.dob DoB
      %th.doj DoJ
      - for i in 1..31
        %th.attendance= "#{i}"
  %tbody
    - j=1
    - @students.each do |student|
      %tr
        %td.sno= j
        %td.id= link_to student.st_id, student
        %td.name= student.name
        %td.gender= student.gender
        %td.program= student.program
        %td.support= student.support
        %td.school= student.school
        -@class = grade(student.grade)
        %td.class= @class
        %td.dob= student.dob
        %td.doj= student.doj
        - for i in 1..31
          %td.attendance= " "
        -j = j+1
#print4
  = link_to 'Add Student', new_student_path, class: "btn btn-default"
%button.btn.btn-default{:onclick => "myFunction()"}
  %small Print
#print5
  %p
    Download:
    = link_to "Excel", students_path(format: "xls"), :support => :support
#print6
  %p
    Import Data:
    = form_tag import_students_path, multipart: true do
      = file_field_tag :file
      = submit_tag "Import"

app/views/students/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Class</Data></Cell>
        <Cell><Data ss:Type="String">School</Data></Cell>
      </Row>
    <% @students.each do |student| %>
      <Row>
        <Cell><Data ss:Type="String"><%= student.st_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.name %></Data></Cell>
        <%@class = grade(student.grade)%>
        <Cell><Data ss:Type="String"><%= @class %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.school %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/students/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1 New Student
    .col-md-6
      = render 'form', student: @student
      = link_to 'Back', students_path
    %br
    %br

app/views/students/show.html.haml
.row
  .col-md-6.col-md-offset-4
    %h1 Student Deatails
    %p#notice= notice
    %p
      %strong Student ID:
      = @student.st_id
    %p
      %strong Name:
      = @student.name
    %p
      %strong Gender:
      = @student.gender
    %p
      %strong Program:
      = @student.program
    %p
      %strong Support:
      = @student.support
    %p
      %strong School:
      = @student.school
    %p
      %strong Class:
      = grade(@student.grade)
    %p
      %strong Date of Birth:
      = @student.dob
    %p
      %strong Date of Joining:
      = @student.doj
      
    = link_to 'Edit', edit_student_path(@student)
    |
    = link_to 'Destroy', @student, method: :delete, data: { confirm: 'Are you sure?' }
    |
    = link_to 'Back', students_path